### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by santoshbt** [shishirregmi/gemini-code-generator#1]
I have followed the instructions and installed the extension to my VS code.
When I write a prompt and press ctrl + shift + 0, nothing is happening.

Please let me know, how to resolve

Thanks

**Comment by shishir-regmi** [comment]
I think you are having one of these issues:

1. Incorrect API KEY 
2. Existing shortcut key

Please verify that the key you entered is valid and also if there is already an existing shortcut key.
