### ISSUE TITLE
No code is generated

### ISSUE THREAD

**Issue by iagranat** [shishirregmi/gemini-code-generator#2]
When calling the "generate code" function, it just deletes the text, without replacing it with any generated content.
I added the api key to the settings. Key is verified to work properly.

I'm using vscode on windows with a remote ssh host running on a linux server.
I also use an extension called Quix AI with the same api key and it seem to work OK.

**Comment by sangamFintech** [comment]
It is working fine in my vs code. I always select what type of language(c#, py, sql, etc) vs code expects right after creating a new unsaved file. Maybe trying this can solve your issue.

Or you can try CTRL + SHIFT + P and select "Generate Code using Gemini API"

**Comment by sangamFintech** [comment]
You can try remapping your keyboard shortcuts

**Comment by shishir-regmi** [comment]
I remapped the default shortcut key to ctrl + shift  + 9.
If the issue still persists please feel free to report it.

**Comment by iagranat** [comment]
I tried with the default shortcut, a custom shortcut (ctrl+shift+alt+a) and also calling the cmd directly from ctrl+shit+p menu.
It was the same each time, the text was deleted and nothing appeared. I also tried to wait 10-20 sec in case it was just a delay with the AI.
are you working with a remote host through ssh?

**Comment by shishirregmi** [comment]
Did the issue persist with different prompts?
I didn't encounter any issues while testing myself. 

If it is possible can you provide me the prompt you submitted?

**Comment by iagranat** [comment]
I just created a new python file (test.py) and wrote in it "write a function for printing a message", highlighted the text, pressed ctrl+shit+p and selected "Generate code...".

I also don't see any relevant logs in the extensions logs. Is there any other place to look for logs of this extension?

**Comment by shishirregmi** [comment]
I tried your prompt but didnot get any error:
![image](https://github.com/shishirregmi/gemini-code-generator/assets/132974474/aa88f0e6-3936-43f7-a86b-643516197a1a)

**Comment by iagranat** [comment]
I don't think the prompt is the problem. I think it's something in the setup that's blocking the extension from working properly.
I tried other Gemini extensions that provide similar functionality and they seem to work better, even on the same prompt.
Is it possible to debug your extension on my side?

**Comment by shishirregmi** [comment]
Yes you are free to provide your help and enhance this extension.
I created this project just for learning how extensions work, so it is bound to have many bugs.

your help would be greatly appreciated.

**Comment by iagranat** [comment]
I'd be happy to help, but I don't have any experience with coding vscode extensions.
I'll see what I can do from the repo.
Is there a way to enable debug logs in the installed extension?
